# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Accounts'),
        ),
    ]
