# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_balance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='operation_type',
            field=models.CharField(choices=[('I', 'Доход'), ('C', 'Расход')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='balance',
            name='operation',
            field=models.CharField(choices=[('I', 'Доход'), ('C', 'Расход')], max_length=1),
        ),
    ]
